version: 2

sources:
  - name: jaffle_shop
    schema: raw
    freshness: # default freshness
      warn_after: { count: 12, period: hour }
      error_after: { count: 24, period: hour }
    loaded_at_field: _etl_loaded_at at time zone 'Europe/Berlin'

    tables:
      - name: raw_customers
        description: One record per customer. Ingested via some API from some 3rd party tool.
        columns:
          - name: id
            description: Unique customer ID generated in some 3rd party tool. Sequential Integer value.
          - name: first_name
            description: First name of a customer. 2nd name onwards is truncated.
          - name: last_name
            description: Last name of a customer.
        freshness: # make this a little more strict
          warn_after: { count: 1, period: minute }
          error_after: { count: 12, period: hour }

      - name: raw_orders # this will use the freshness defined above

      - name: raw_customer_addresses

      - name: raw_analytics

  - name: cashing_system
    database: jaffle_shop
    schema: raw
    freshness: # default freshness
      warn_after: { count: 12, period: hour }
      error_after: { count: 24, period: hour }
    loaded_at_field: _etl_loaded_at at time zone 'Europe/Berlin'
    tables:
      - name: raw_payments
